### ISSUE TITLE
Error when running 'backup' and 'whole-backup'

### ISSUE THREAD

**Issue by Wozarib** [Ahtenus/minecraft-init#22]
Hi there,

When running either 'backup' or 'whole-backup' I receive the following error, resulting in the server hanging:

2011-12-19 10:36:01 [INFO] [35m[Server] Backing up world.[0m
2011-12-19 10:36:01 [INFO] CONSOLE: Disabling level saving..[0m
2011-12-19 10:36:01 [INFO] CONSOLE: Forcing save..[0m
2011-12-19 10:36:01 [INFO] CONSOLE: Save complete.[0m
2011-12-19 10:36:51 [INFO] CONSOLE: Enabling level saving..[0m
2011-12-19 10:36:51 [INFO] [35m[Server] Backup complete.[0m
2011-12-19 10:36:51 [SEVERE] net.minecraft.server.WorldConlictException: The save is being accessed from another location, aborting
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.WorldNBTStorage.checkSession(WorldNBTStorage.java:68)
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.World.l(World.java:2641)
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.World.y(World.java:274)
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.World.save(World.java:264)
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.World.doTick(World.java:1735)
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:514)
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
2011-12-19 10:36:51 [SEVERE]    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)
2011-12-19 10:36:51 [SEVERE] Unexpected exception
net.minecraft.server.WorldConlictException: The save is being accessed from another location, aborting
    at net.minecraft.server.WorldNBTStorage.checkSession(WorldNBTStorage.java:68)
    at net.minecraft.server.World.l(World.java:2641)
    at net.minecraft.server.World.y(World.java:274)
    at net.minecraft.server.World.save(World.java:264)
    at net.minecraft.server.World.doTick(World.java:1735)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:514)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:425)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:457)

**Comment by flaminSaganaki** [comment]
interesting...
maybe check to see that the directories u specified in the script are... idk. free?
Also, just a wild guess, but did u accidentally start up another instance of the server, which could be still trying to save on the save world files.. hence their innaccessibilty.
Just tryin to help

**Comment by jjcf89** [comment]
This should be fixed with the latest update.  Whole-backup now complains if server is running and backup worked just fine for me.
