### ISSUE TITLE
Worldgaurd not workign at all

### ISSUE THREAD

**Issue by THUNDERGROOVE** [Ahtenus/minecraft-init#75]
When I run Bukkit RB from your script and attempt to define a new area (In WorldGaurd) I get several errors in the console 

2012-05-29 09:05:30 [SEVERE] [WorldGuard] Error loading regions for world "Town": java.io.FileNotFoundException: /home/nick/mc/plugins/WorldGuard/worlds/Town/regions.yml
    /home/nick/mc/plugins/WorldGuard/worlds/Town/regions.yml
2012-05-29 09:05:30 [SEVERE] java.io.FileNotFoundException: /home/nick/mc/plugins/WorldGuard/worlds/Town/regions.yml
2012-05-29 09:05:30 [SEVERE]    at com.sk89q.worldguard.protection.databases.YAMLDatabase.<init>(YAMLDatabase.java:60)
2012-05-29 09:05:30 [SEVERE]    at com.sk89q.worldguard.protection.GlobalRegionManager.load(GlobalRegionManager.java:142)
2012-05-29 09:05:30 [SEVERE]    at com.sk89q.worldguard.protection.GlobalRegionManager.get(GlobalRegionManager.java:229)
2012-05-29 09:05:30 [SEVERE]    at com.sk89q.worldguard.bukkit.FlagStateManager.run(FlagStateManager.java:86)
2012-05-29 09:05:30 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-05-29 09:05:30 [SEVERE]    at java.lang.Thread.run(Thread.java:679)
2012-05-29 09:05:30 [SEVERE] java.lang.NullPointerException
2012-05-29 09:05:30 [SEVERE]    at com.sk89q.worldguard.bukkit.FlagStateManager.run(FlagStateManager.java:88)
2012-05-29 09:05:30 [SEVERE]    at org.bukkit.craftbukkit.scheduler.CraftWorker.run(CraftWorker.java:34)
2012-05-29 09:05:30 [SEVERE]    at java.lang.Thread.run(Thread.java:679)

But when I run it just with the basic java -jar craftbukkit.jar everything works fine

also I haven't been able to import worlds with Multiverse and whenever I login I end up in a different world everytime...

**Comment by xLRDx** [comment]
What distro are you using?

**Comment by THUNDERGROOVE** [comment]
Ubuntu 12.04 LTS.
My whole server folder and world folders are 0777 recursively as well

**Comment by Rovanion** [comment]
It does not have to do with permissions, the error is: java.io.FileNotFoundException: /home/nick/mc/plugins/WorldGuard/worlds/Town/regions.yml.

This is the file that is not found, it has to do with the plugin WorldGuard and not the initscript.

Protip: Check if the file is there.
