### ISSUE TITLE
Changing Java parameters ..

### ISSUE THREAD

**Issue by mkromann** [Ahtenus/minecraft-init#90]
Hello,

I'd like to change the java starting parameters but it causes quite some trouble for me. Problem seems to be that if I don't include $MAXMEM, $INITMEM and $CPU_COUNT the script simply stops working. Is there a workaround for that?

This is the original:
java -Xmx$MAXMEM -Xms$INITMEM -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -jar $SERVICE nogui

I'd like to change it to:
java -Xmx$MAXMEM -Xincgc XX:+UseG1GC -jar $SERVICE nogui

How do I do this?

The reason for the change is based on the post by TnT from Bukkit (read the last posts by TnT http://forums.bukkit.org/threads/how-to-improve-mincraft-server-performance.662/). I've done some testing and I get much better performance with the last-mentioned parameters.

Also what does nogui do?

**Comment by sockenklaus** [comment]
It would be nice if you could post some kind of error log... Your invokation doesn't look completely wrong to me, so i don't see a reason why this shouldn't work.

**Comment by mkromann** [comment]
Of course.
I don't really get any errors, but this is what happens:
1. Stop the server.
2. Replace the java parameters in the config.
3. Execute the start command.
4. The script reports that the server has started (is running).
5. I try to access screen but it reports that that no server is running. (also no java processes are running)
6. Reboot the system.
7. Server starts (automatic startup seems to function).
8. Server continuous to run but no commands work (thus no backup or stopping the server).

**Comment by sockenklaus** [comment]
Okay, is anything in $MCPATH/Server.log?

**Comment by mkromann** [comment]
No, nothing .. the server doesn't start because craftbukkit.jar is not executed at any time.

Also, if I start the server through a reboot the console commands (save-off, save-on etc) from the script stops.

**Comment by sockenklaus** [comment]
`java -Xmx$MAXMEM -Xincgc XX:+UseG1GC -jar $SERVICE nogui`

I just realized, that there's a **minus** missing in front of the parameter `XX:+UseG1GC`. Is this intentional? :)

**Comment by mkromann** [comment]
Hm, most likely not intentional .. I tried changing it but it did no difference. Anyway, I tried a different approach this time which caused the server to crash. I changed the parameters while the server was running, and then tried to restart the server twice which produced the following output:

minecraft@Ubuntu-1110-oneiric-64-minimal:~$ /etc/init.d/minecraft restart
No running server, starting it...
created link for world_large
created link for world_large_nether
created link for world_large_the_end
created link for world_main
created link for world_main_nether
created link for world_main_the_end
world_large copied to ram
craftbukkit.jar is running.
minecraft@Ubuntu-1110-oneiric-64-minimal:~$ /etc/init.d/minecraft restart
No running server, starting it...
created link for world_large
created link for world_large_nether
created link for world_large_the_end
created link for world_main
created link for world_main_nether
created link for world_main_the_end
world_large copied to ram
craftbukkit.jar is running.
minecraft@Ubuntu-1110-oneiric-64-minimal:~$

As you can see it says that no server is running and attempts to start a new one. No server is actually started but as I said it caused the already running server to crash. This is the crash report:

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/17/12 11:43 PM
Description: Exception in server tick loop

net.minecraft.server.ExceptionWorldConflict: The save is being accessed from another location, aborting
    at net.minecraft.server.WorldNBTStorage.checkSession(WorldNBTStorage.java:70)
    at net.minecraft.server.World.B(World.java:2473)
    at net.minecraft.server.WorldServer.a(WorldServer.java:676)
    at net.minecraft.server.WorldServer.save(WorldServer.java:666)
    at net.minecraft.server.MinecraftServer.saveChunks(MinecraftServer.java:310)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:478)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:406)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)

Relevant Details:
- Minecraft Version: 1.3.2
- Operating System: Linux (amd64) version 3.0.0-12-server
- Java Version: 1.7.0_03, Oracle Corporation
- Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
- Memory: 3743304584 bytes (3569 MB) / 4242669568 bytes (4046 MB) up to 23570022400 bytes (22478 MB)
- JVM Flags: 6 total; -Xmx22528M -Xms4096M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=6 -XX:+AggressiveOpts

**Comment by sockenklaus** [comment]
Okay... if i understand this correctly, the following is happening:
1. Your server is running
2. You're trying to restart the server
3. **The script does not detect, that there is an instance already running**
4. The scripts tries to start another instance
5. This leads to a JavaException an crashes your system

So...:
Would you like to post the output of `ps ax`, while your server is running (right after reboot)? I don't think, that the java paremeters are your problem or the start of the server itself, but the detection, wether an instance of the server is already running or not.

**Comment by mkromann** [comment]
Between 1 and 2 I change the Java parameters from:

java -Xmx$MAXMEM -Xms$INITMEM -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=$CPU_COUNT -XX:+AggressiveOpts -jar $SERVICE nogui

to:

java -Xmx$MAXMEM -Xincgc -XX:+UseG1GC -jar $SERVICE nogui

I'll provide the output of px ax as soon as possible, which will be tomorrow.

I agree that it seems to be the detection that is failing. How that is connected with me changing the parameters is weird though. Whenever I change the parameters back it perform with no problems.

Also I'd like to thank you for taken the time to assist.

**Comment by sockenklaus** [comment]
Does this error occur, when you don't change the parameters between 1 and 2?

**Comment by mkromann** [comment]
No, it does not.

I figured I didn't have the latest version of the script so I tried to upgrade to see if it addressed the problem. Sadly it didn't and at this point I am not even able to start the server with the new parameters through a system reboot. Therefore I cannot provide you with any ps ax, when the server has rebooted. What I can provide, is a ps ax output with the standard parameters:

  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:01 /sbin/init
    2 ?        S      0:00 [kthreadd]
    3 ?        S      0:00 [ksoftirqd/0]
    4 ?        S      0:00 [kworker/0:0]
    5 ?        S      0:00 [kworker/u:0]
    6 ?        S      0:00 [migration/0]
    7 ?        S      0:00 [migration/1]
    8 ?        S      0:00 [kworker/1:0]
    9 ?        S      0:00 [ksoftirqd/1]
   10 ?        S      0:00 [kworker/0:1]
   11 ?        S      0:00 [migration/2]
   12 ?        S      0:00 [kworker/2:0]
   13 ?        S      0:00 [ksoftirqd/2]
   14 ?        S      0:00 [migration/3]
   15 ?        S      0:00 [kworker/3:0]
   16 ?        S      0:00 [ksoftirqd/3]
   17 ?        S      0:00 [migration/4]
   18 ?        S      0:00 [kworker/4:0]
   19 ?        S      0:00 [ksoftirqd/4]
   20 ?        S      0:00 [migration/5]
   21 ?        S      0:00 [kworker/5:0]
   22 ?        S      0:00 [ksoftirqd/5]
   23 ?        S      0:00 [migration/6]
   24 ?        S      0:00 [kworker/6:0]
   25 ?        S      0:00 [ksoftirqd/6]
   26 ?        S      0:00 [migration/7]
   27 ?        S      0:00 [kworker/7:0]
   28 ?        S      0:00 [ksoftirqd/7]
   29 ?        S<     0:00 [cpuset]
   30 ?        S<     0:00 [khelper]
   31 ?        S<     0:00 [netns]
   32 ?        S      0:00 [kworker/u:1]
   33 ?        S      0:00 [sync_supers]
   34 ?        S      0:00 [bdi-default]
   35 ?        S<     0:00 [kintegrityd]
   36 ?        S<     0:00 [kblockd]
   37 ?        S<     0:00 [ata_sff]
   38 ?        S      0:00 [khubd]
   39 ?        S<     0:00 [md]
   41 ?        S      0:00 [khungtaskd]
   42 ?        S      0:00 [kswapd0]
   43 ?        SN     0:00 [ksmd]
   44 ?        SN     0:00 [khugepaged]
   45 ?        S      0:00 [fsnotify_mark]
   46 ?        S      0:00 [ecryptfs-kthrea]
   47 ?        S<     0:00 [crypto]
   55 ?        S<     0:00 [kthrotld]
   74 ?        S      0:00 [kworker/4:1]
  212 ?        S      0:00 [scsi_eh_0]
  216 ?        S      0:00 [kworker/3:1]
  217 ?        S      0:00 [scsi_eh_1]
  218 ?        S      0:00 [scsi_eh_2]
  219 ?        S      0:00 [scsi_eh_3]
  220 ?        S      0:00 [scsi_eh_4]
  221 ?        S      0:00 [scsi_eh_5]
  225 ?        S      0:00 [kworker/u:2]
  227 ?        S      0:00 [kworker/u:3]
  228 ?        S      0:00 [kworker/u:4]
  229 ?        S      0:00 [kworker/u:5]
  230 ?        S      0:00 [kworker/u:6]
  231 ?        S      0:00 [kworker/0:2]
  235 ?        S      0:00 [kworker/7:1]
  236 ?        S      0:00 [kworker/6:1]
  237 ?        S      0:00 [kworker/u:7]
  272 ?        S      0:00 [md1_raid1]
  282 ?        S      0:00 [md0_raid1]
  286 ?        S      0:00 [md2_raid1]
  290 ?        S      0:00 [md3_raid1]
  341 ?        S      0:00 [kworker/2:1]
  342 ?        R      0:00 [kworker/1:1]
  343 ?        S      0:00 [kworker/5:1]
  348 ?        S      0:00 [jbd2/md2-8]
  349 ?        S<     0:00 [ext4-dio-unwrit]
  408 ?        S      0:00 upstart-udev-bridge --daemon
  411 ?        Ss     0:00 udevd --daemon
  537 ?        S      0:00 [irq/21-mei]
  601 ?        S      0:00 udevd --daemon
  602 ?        S      0:00 udevd --daemon
  659 ?        S      0:00 upstart-socket-bridge --daemon
  749 ?        S      0:00 [jbd2/md3-8]
  750 ?        S<     0:00 [ext4-dio-unwrit]
  757 ?        S      0:00 [kjournald]
  778 ?        Ss     0:00 /usr/sbin/sshd -D
  783 ?        Sl     0:00 rsyslogd -c5
  788 ?        Ss     0:00 dbus-daemon --system --fork --activation=upstart
  859 tty4     Ss+    0:00 /sbin/getty -8 38400 tty4
  864 tty5     Ss+    0:00 /sbin/getty -8 38400 tty5
  868 ?        Ss     0:00 su -s /bin/sh -c exec "$0" "$@" revealcloud -- /usr/l
  873 tty2     Ss+    0:00 /sbin/getty -8 38400 tty2
  874 tty3     Ss+    0:00 /sbin/getty -8 38400 tty3
  880 tty6     Ss+    0:00 /sbin/getty -8 38400 tty6
  889 ?        Ss     0:00 acpid -c /etc/acpi/events -s /var/run/acpid.socket
  897 ?        Ss     0:00 /usr/sbin/irqbalance
  910 ?        Ssl    0:00 /usr/sbin/mysqld
  930 ?        Ss     0:00 cron
  931 ?        Ss     0:00 atd
  932 ?        Sl     0:00 /usr/local/revealcloud/revealcloud -a api.copperegg.c
 1195 ?        S      0:00 [flush-9:1]
 1196 ?        S      0:00 [flush-9:2]
 1197 ?        S      0:00 [flush-9:3]
 1203 ?        Ss     0:00 sshd: minecraft [priv]
 1205 ?        Sl     0:00 /usr/local/revealcloud/revealcloud -a api.copperegg.c
 1239 ?        S      0:00 sshd: minecraft@notty
 1240 ?        Ss     0:00 /usr/lib/openssh/sftp-server
 1241 ?        Ss     0:00 sshd: minecraft [priv]
 1265 ?        S      0:00 sshd: minecraft@pts/1
 1266 pts/1    Ss     0:00 -bash
 1366 ?        Ss     0:00 sshd: minecraft [priv]
 1390 ?        S      0:00 sshd: minecraft@notty
 1391 ?        Ss     0:00 /usr/lib/openssh/sftp-server
 1437 ?        Ss     0:00 SCREEN -dmS minecraft java -Xmx22528M -Xms4096M -XX:+
 1442 pts/2    Ssl+   1:15 java -Xmx22528M -Xms4096M -XX:+UseConcMarkSweepGC -XX
 1465 ?        Ss     0:00 /sbin/mdadm --monitor --pid-file /var/run/mdadm/monit
 1528 tty1     Ss+    0:00 /sbin/getty -8 38400 tty1
 1640 pts/1    R+     0:00 ps ax

**Comment by lottspot** [comment]
Processes 1437 and 1442 seem to reflect sockenklaus' suspicion that minecraft has been invoked and is running... Try sourcing your config file (. /path/to/config) and run ~$ ps ax | grep "$SCREEN $INVOCATION" then run ~$ echo $? and check the output.

**Comment by mkromann** [comment]
Isn't that what it's supposed to look like? As stated, I am now unable to start the server with the new parameters and therefore provided the output of ps ax, when the server was running with the standard parameters (might be useless). Again, the server cannot be started when I change the parameters. When I do "/etc/init.d/minecraft start" it doesn't start the server.

**Comment by lottspot** [comment]
My mistake, I misunderstood the context under which that output was produced.

**Comment by sockenklaus** [comment]
Oh, i've been so stupid...
You simply **cannot** change the invokation while the server is running. The function `is_running()` basically checks, whether the invokation defined in `config` appears in `ps ax` or not.
So if you change the invokation during runtime, this will cause the function to fail and breaks the init-script.

What you have to do is:
1. Shutdown the server: `/etc/init.d/minecraft stop`
2. Change the invokation to whatever you like
2. Start the server: `/etc/init.d/minecraft start`

This should work fine, as long as your invokation is valid. :)

**Comment by mkromann** [comment]
You know what, it has nothing to do with the script .. apparently it was the invovation which was bad. -XX:+UseG1GC was the cause so I've left it out, and everything is working now. I'll check out was exactly was going wrong at a later time but for now it's brilliant. The server is running remarkably better with the new parameters. 

I am in no way an expert but maybe we should consider changing the default parameters?

Again, thank you for helping me out :-)

**Comment by sockenklaus** [comment]
I'm happy it's finally working. :)

So your invocation now looks like this?
`java -Xmx$MAXMEM -Xincgc -jar $SERVICE nogui`

Since i'm not a java expert, i don't know, which are the optimal parameters, but i'd say, that the java vm knows best, how to optimize and run the program, it's given, so i prefer the motto: "Less parameters cause less trouble" ;)
So this would support your point.

It would be interesting, if @Ahtenus could explain, why he chose these default parameters in the first place.

**Comment by mkromann** [comment]
It's sort of based off of what TnT said in the thread I linked in the initial post. It's on the last pages .. it's nothing in-depth but I just thought I'd try it and it seems to work better. What I noticed is that my CPU works quite a bit more but I got rid of random 'lags' where blocks would reappear for a second at times.

Teleportation and chunk loading also got a lot smoother ..
